# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test

# Definir o Deploy no Heroku
deploy:
- provider: heroku
  api_key: $apikeyheroku
  edge: true
  app: developslab-galindo
  on:
    branch: main
- provider: gae
  keyfile: ../lab-devops-cloud-galindo-a39ff5f614fd.json
  project: lab-devops-cloud-galindo
  on:
    branch: main
before_install:
- openssl aes-256-cbc -K $encrypted_c0fe2e4b1c11_key -iv $encrypted_c0fe2e4b1c11_iv
  -in lab-devops-cloud-galindo-a39ff5f614fd.json.enc -out /vagrant/lab-devops-cloud-galindo-a39ff5f614fd.json
  -d
